//Bird Data
let birdData = [
  {
    name: "stellers-jay",
    image: "assets/bird-pics/stellers-jay.jfif",
    correctAnswer: "STELLER'S JAY",
    options: [
      "BLUE JAY",
      "STELLER'S JAY",
      "NORTHERN CARDINAL",
      "EURASIAN MAGPIE",
    ],
    tips: [
      "Dark blue and black plumge with a crest",
      "Small spots on forehead and near eyes",
      "Broad, rounded wings",
      "A harsh 'shack, shack, shack' sound",
    ],
    alt: "Steller's jay perched on a tree branch",
  },
  {
    name: "brown-headed-cowbird",
    image: "assets/bird-pics/brown-headed-cowbird.jfif",
    correctAnswer: "BROWN-HEADED COWBIRD",
    options: [
      "BROWN-HEADED COWBIRD",
      "BREWER'S BLACKBIRD",
      "COMMON GRACKLE",
      "BRONZED COWBIRD",
    ],
    tips: ["fake tip"],
    alt: "Brown-headed cowbird",
  },
  {
    name: "coopers-hawk",
    image: "assets/bird-pics/coopers-hawk.jfif",
    correctAnswer: "COOPER'S HAWK",
    options: [
      "COOPER'S HAWK",
      "SHARP-SHINNED HAWK",
      "PEREGRINE FALCOLN",
      "AMERICAN GOSHAWK",
    ],
    tips: ["fake tip"],
    alt: "Cooper's Hawk",
  },
  {
    name: "dark-eyed-junco",
    image: "assets/bird-pics/dark-eyed-junco",
    correctAnswer: "DARK-EYED JUNCO",
    options: [
      "BLACK-CAPPED CHICKADEE",
      "DARK-EYED JUNCO",
      "BLACK PHOEBE",
      "SPOTTED TOWHEE",
    ],
    tips: ["fake tip"],
    alt: "Dark-eyed junco",
  },
  {
    name: "great-blue-heron",
    image: "assets/bird-pics/great-blue-heron.jfif",
    correctAnswer: "GREAT BLUE HERON",
    options: [
      "GREAT BLUE HERON",
      "LITTLE BLUE HERON",
      "TRICOLORED HERON",
      "NIGHT HERON",
    ],
    tips: ["fake tip"],
    alt: "Great blue heron",
  },
  {
    name: "northern-cardinal",
    image: "assets/bird-pics/northern-cardinal.jfif",
    correctAnswer: "NORTHERN CARDINAL",
    options: [
      "NORTHERN CARDINAL",
      "SUMMER TANAGER",
      "SCARLET TANAGER",
      "VERMILION CARDINAL",
    ],
    tips: ["fake tip"],
    alt: "Northern cardinal",
  },
  {
    name: "northern-flicker",
    image: "assets/bird-pics/northern-flicker.jfif",
    correctAnswer: "NORTHERN FLICKER",
    options: [
      "PILEATED WOODPECKER",
      "GILDED FLICKER",
      "NORTHERN FLICKER",
      "GILA WOODPECKER",
    ],
    tips: ["fake tip"],
    alt: "Norther flicker",
  },
  {
    name: "osprey",
    image: "assets/bird-pics/osprey.jfif",
    correctAnswer: "OSPREY",
    options: ["OSPREY", "RED-TAILED HAWK", "BALD EAGLE", "GOLDEN EAGLE"],
    tips: ["fake tip"],
    alt: "Osprey soaring over body of water",
  },
  {
    name: "sandwich-tern",
    image: "assets/bird-pics/sandwich-tern.jfif",
    correctAnswer: "SANDWICH TERN",
    options: ["COMMON TERN", "ROYAL TERN", "ELEGANT TERN", "SANDWICH TERN"],
    tips: ["fake tip"],
    alt: "Sandwich tern",
  },
  {
    name: "scissor-tailed-flycatcher",
    image: "assets/bird-pics/scissor-tailed-flycatcher.jfif",
    correctAnswer: "SCISSOR-TAILED FLYCATCHER",
    options: [
      "SCISSOR-TAILED FLYCATCHER",
      "WESTERN KINGBIRD",
      "FORK-TAILED FLYCATCHER",
      "EASTERN KINGBIRD",
    ],
    tips: ["fake tip"],
    alt: "Scissor tailed flycatcher perched on a fence",
  },
];
