//Bird Data

let birdData = [
  {
    name: "american-robin",
    image: "assets/bird-pics/american-robin.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:2009-03-13,_American_robin_(Turdus_migratorius),_001.jpg" target="_blank" rel="noopener noreferrer">Steven Pavlov</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "AMERICAN ROBIN",
    options: [
      "AMERICAN ROBIN",
      "SPOTTED TOWHEE",
      "VARIED THRUSH",
      "EASTERN TOWHEE",
    ],
    tips: [
      "Fairly large songbird with round body, long legs, and longish tail (eBird)",
      "Gray above with warm orange underparts and blackish head (eBird)",
      "Hops across lawns and stands erect with its bill often tilted upward (eBird)",
      "Common across North America in gardens, parks, yards, golf courses, fields, pastures, and many other wooded habitats (eBird)",
    ],
    alt: "American robin standing in grass",
  },
  {
    name: "barn-swallow",
    image: "assets/bird-pics/barn-swallow.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Barn_Swallow_(34869731935).jpg" target="_blank" rel="noopener noreferrer">U.S. Fish and Wildlife Service - Midwest Region</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "BARN SWALLOW",
    options: ["BARN SWALLOW", "TREE SWALLOW", "CLIFF SWALLOW", "PURPLE MARTIN"],
    tips: [
      "A fairly large, colorful swallow with long, forked tail and dark rump (eBird)",
      "Iridescent navy-blue above with a rich orange throat and forehead (eBird)",
      "Underparts vary across range, from bright buffy-orange to whitish (eBird)",
      "Occurs in any open habitat, especially large fields and wetlands, often seen foraging in flocks (eBird)",
    ],
    alt: "Barn swallow perched on a wire",
  },
  {
    name: "belted-kingfisher",
    image: "assets/bird-pics/belted-kingfisher.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20240821_belted_kingfisher_keeney_cove_PD201201.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BELTED KINGFISHER",
    options: [
      "BELTED KINGFISHER",
      "GREEN KINGFISHER",
      "RINGED KINGFISHER",
      "BLUE JAY",
    ],
    tips: [
      "Stocky and large-headed with a shaggy crest (eBird)",
      "Bill is long, straight, thick, and pointed (eBird)",
      "Powder blue above with white underparts and blue breast band (eBird)",
      "Females have additional rusty band across belly (eBird)",
    ],
    alt: "Belted kingfisher perched on branch",
  },
  {
    name: "black-capped-chickadee",
    image: "assets/bird-pics/black-capped-chickadee.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20220923_black_capped_chickadee_posing_at_canoe_meadows_PND1343-DeNoiseAI-standard-SharpenAI-Standard.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BLACK-CAPPED CHICKADEE",
    options: [
      "BLACK-CAPPED CHICKADEE",
      "CAROLINA CHICKADEE",
      "MOUNTAIN CHICKADEE",
      "BOREAL CHICKADEE",
    ],
    tips: [
      "Tiny, plump-bodied, and big-headed (eBird)",
      "Gray overall with light buffy flanks and a contrasting head pattern: black cap, white cheek, and black throat (eBird)",
      "Short, stubby bill (eBird)",
      "Nearly identical to Carolina Chickadee, but range barely overlaps (eBird)",
    ],
    alt: "Black-capped chickadee perched in branches of a tree",
  },
  {
    name: "blue-jay",
    image: "assets/bird-pics/blue-jay.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20250126_blue_jay_housatonic_valley_wma_PD204015.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BLUE JAY",
    options: ["BLUE JAY", "STELLER'S JAY", "FLORIDA SCRUB-JAY", "GREEN JAY"],
    tips: [
      "Found year-round throughout most of eastern North America (eBird)",
      "Bright blue above and pale gray below with a fluffy crest (eBird)",
      "Black necklace and black and white markings on the wings and tail (eBird)",
      "Frequently visits bird feeders, where it is often aggressive towards other birds (eBird)",
    ],
    alt: "Blue jay perched in a tree",
  },
  {
    name: "brown-headed-cowbird",
    image: "assets/bird-pics/brown-headed-cowbird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Brown-headed_cowbird_male_(71126).jpg" target="_blank" rel="noopener noreferrer">Rhododendrites</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BROWN-HEADED COWBIRD",
    options: [
      "BROWN-HEADED COWBIRD",
      "BREWER'S BLACKBIRD",
      "COMMON GRACKLE",
      "BRONZED COWBIRD",
    ],
    tips: [
      "Stout bill, short tail and stocky body (eBird)",
      "Males are glossy black with chocolate brown head (eBird)",
      "Females are gray-brown overall, without bold streaks, but slightly paler throat (eBird)",
      "Forages by walking on the ground (eBird)",
    ],
    alt: "Brown-headed cowbird on branch",
  },
  {
    name: "brown-thrasher",
    image: "assets/bird-pics/brown-thrasher.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Brown_thrasher_in_CP_(02147).jpg" target="_blank" rel="noopener noreferrer">Rhododendrites</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0 target="_blank" rel="noopener noreferrer"">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BROWN THRASHER",
    options: [
      "BROWN THRASHER",
      "NORTHERN MOCKINGBIRD",
      "GRAY CATBIRD",
      "CURVE-BILLED THRASHER",
    ],
    tips: [
      "Fairly large and very long-tailed, with bright rufous upperparts and heavily streaked underparts (eBird)",
      "White wingbars, staring yellow eyes, and slightly decurved bill (eBird)",
      "Usually skulky and difficult to see in shrubby habitats (eBird)",
      "Most similar to Long-billed Thrasher, but almost no range overlap (eBird)",
    ],
    alt: "Brown thrasher standing in snow",
  },
  {
    name: "canada-goose",
    image: "assets/bird-pics/canada-goose.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20231208_canada_goose_goodwin_dock_PD101660.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "CANADA GOOSE",
    options: [
      "CANADA GOOSE",
      "CACKLING GOOSE",
      "GREATER WHITE-FRONTED GOOSE",
      "SNOW GOOSE",
    ],
    tips: [
      "A large brown goose with a black neck and white chinstrap (eBird)",
      "Occurs in any open or wetland habitat, from city parks and golf courses to pristine marshes and Arctic tundra (eBird)",
      "Abundant and widespread throughout the U.S. and Canada (eBird)",
      "Listen for loud honking calls, especially as flocks migrate overhead in the classic V formation (eBird)",
    ],
    alt: "Canada goose swimming",
  },
  {
    name: "cedar-waxwing",
    image: "assets/bird-pics/cedar-waxwing.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20230608_cedar_waxwing_PD26635.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "CEDAR WAXWING",
    options: [
      "CEDAR WAXWING",
      "BOHEMIAN WAXWING",
      "NORTHERN CARDINAL",
      "EUROPEAN STARLING",
    ],
    tips: [
      "Plump, smooth-plumaged bird (eBird)",
      "Adults have a sleek crest, black mask, pale yellow wash on the belly, and yellow-tipped tail (eBird)",
      "Juveniles are drabber than adults, with coarse streaking on the breast and a reduced mask (eBird)",
      "Often gathers in large flocks, especially around fruiting trees (eBird)",
    ],
    alt: "Cedar waxwing perched on branch",
  },
  {
    name: "coopers-hawk",
    image: "assets/bird-pics/coopers-hawk.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Juvenile_cooper%27s_hawk.jpg" target="_blank" rel="noopener noreferrer">https://www.flickr.com/people/sherseydc/</a>, <a href="https://creativecommons.org/licenses/by-sa/1.0" target="_blank" rel="noopener noreferrer">CC BY-SA 1.0</a>, via Wikimedia Commons`,
    correctAnswer: "COOPER'S HAWK",
    options: [
      "COOPER'S HAWK",
      "SHARP-SHINNED HAWK",
      "RED-SHOULDERED HAWK",
      "NORTHERN GOSHAWK",
    ],
    tips: [
      "Small to medium-sized hawk with relatively short rounded wings and rounded tail (eBird)",
      "Adults are gray above with pale orange barring below; immatures are browner and streaky (eBird)",
      "Very similar to Sharp-shinned Hawk, but larger with bigger head and deeper, slower wingbeats (eBird)",
      "Often stalks feeders in search of prey (eBird)",
    ],

    alt: "Cooper's hawk perched on branch in park",
  },
  {
    name: "dark-eyed-junco",
    image: "assets/bird-pics/dark-eyed-junco.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20231109_dark_eyed_junco_old_south_cemetery_PND09024.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "DARK-EYED JUNCO",
    options: [
      "DARK-EYED JUNCO",
      "SONG SPARROW",
      "WHITE-THROATED SPARROW",
      "CHIPPING SPARROW",
    ],
    tips: [
      "Generally patterned with gray, white, and shades of tan (eBird)",
      "Pinkish bills and white outer tail feathers (eBird)",
      "Found in any wooded habitat in the winter, often in flocks (eBird)",
      "Usually forages on the ground for seeds, but also fond of brushy thickets or weedy fields (eBird)",
    ],
    alt: "Dark-eyed Junco perched on gravestone",
  },
  {
    name: "downy-woodpecker",
    image: "assets/bird-pics/downy-woodpecker.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Downy_woodpecker_in_GWC_(33941).jpg" target="_blank" rel="noopener noreferrer">Rhododendrites</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "DOWNY WOODPECKER",
    options: [
      "DOWNY WOODPECKER",
      "HAIRY WOODPECKER",
      "RED-COCKADED WOODPECKER",
      "YELLOW-BELLIED SAPSUCKER",
    ],
    tips: [
      "Black-and-white plumage (eBird)",
      "Very short bill, much shorter than the length of the head (eBird)",
      "Small black markings on the white outer tail feathers (eBird)",
      "Familiar visitor to backyard feeders, especially fond of suet (eBird)",
    ],
    alt: "Downy woodpecker perched on tree branch",
  },
  {
    name: "eastern-bluebird",
    image: "assets/bird-pics/eastern-bluebird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Male_Eastern_Bluebird_from_below.jpg" target="_blank" rel="noopener noreferrer">Dehaan</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "EASTERN BLUEBIRD",
    options: [
      "EASTERN BLUEBIRD",
      "WESTERN BLUEBIRD",
      "MOUNTAIN BLUEBIRD",
      "BARN SWALLOW",
    ],
    tips: [
      "Adult males are striking royal blue above with bright orange throat and breast and bright white belly (eBird)",
      "Females are paler overall; grayish with orange on breast and sides of neck, and white belly (eBird)",
      "Favors fields and open woods (eBird)",
      "Frequently perches on wires or fence posts (eBird)",
    ],
    alt: "Eastern bluebird perched on fence post",
  },
  {
    name: "european-starling",
    image: "assets/bird-pics/european-starling.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Toulouse_-_Sturnus_vulgaris_-_2012-02-26_-_1.jpg" target="_blank" rel="noopener noreferrer">PierreSelim</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "EUROPEAN STARLING",
    options: [
      "EUROPEAN STARLING",
      "COMMON GRACKLE",
      "BREWER'S BLACKBIRD",
      "RED-WINGED BLACKBIRD",
    ],
    tips: [
      "Stocky and dark overall with short tail and triangular wings (eBird)",
      "In breeding season, look for purple and green iridescence and a yellow bill (eBird)",
      "Often abundant, gathering in large flocks in open agricultural areas and towns and cities (eBird)",
      "Visits feeders, where it is often aggressive towards other birds (eBird)",
    ],
    alt: "European starling in grass",
  },
  {
    name: "great-blue-heron",
    image: "assets/bird-pics/great-blue-heron.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Ardea_herodias5.jpg" target="_blank" rel="noopener noreferrer">&quot;Mike&quot; Michael L. Baird</a>, <a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener noreferrer">CC BY 2.0</a>, via Wikimedia Commons`,
    correctAnswer: "GREAT BLUE HERON",
    options: [
      "GREAT BLUE HERON",
      "SANDHILL CRANE",
      "LITTLE BLUE HERON",
      "TRICOLORED HERON",
    ],
    tips: [
      "Huge gray heron, no other similar species in range (eBird)",
      "Large yellow-orange bill, short black plumes on head, and black and chestnut pattern on shoulder (eBird)",
      "Immatures are more brownish than adults, and have a dark crown (eBird)",
      "Occurs in almost any wetland habitat, from small ponds to marshes to saltwater bays (eBird)",
    ],
    alt: "Great blue heron standing in lake",
  },
  {
    name: "house-finch",
    image: "assets/bird-pics/house-finch.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:House_Finch-27527-2.jpg" target="_blank" rel="noopener noreferrer">Ken Thomas</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "HOUSE FINCH",
    options: ["HOUSE FINCH", "PURPLE FINCH", "CASSIN'S FINCH", "PINE SISKIN"],
    tips: [
      "Males vary in shades and intensity of red- some are yellow or orange (eBird)",
      "Females are drab gray-brown overall with plain faces and blurry streaks on underparts (eBird)",
      "Red color is mostly restricted to head and upper chest, contrasting with cold gray-brown nape, back, and wings (eBird)",
      "Pale sides show distinct brown streaks, lacking red tones (eBird)",
    ],
    alt: "House finch perched on branch",
  },
  {
    name: "killdeer",
    image: "assets/bird-pics/killdeer.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Killdeer_(Charadrius_vociferus).jpg" target="_blank" rel="noopener noreferrer">hart_curt</a>, <a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener noreferrer">CC BY 2.0</a>, via Wikimedia Commons`,
    correctAnswer: "KILLDEER",
    options: [
      "KILLDEER",
      "SPOTTED SANDPIPER",
      "SEMIPALMATED PLOVER",
      "WILSON'S PLOVER",
    ],
    tips: [
      "Slender shape with long wings and tail (eBird)",
      "Two black breast bands, unique among plovers in its range (eBird)",
      "Adults perform broken-wing displays to distract predators from their nests and young (eBird)",
      "Can be very vocal; listen for loud namesake “kill-deer” call (eBird)",
    ],
    alt: "Killdeer on rocky beach",
  },
  {
    name: "mallard",
    image: "assets/bird-pics/mallard.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Mallard_Ducks_at_Downsview_Park_13.jpg" target="_blank" rel="noopener noreferrer">Fabian Roudra Baroi</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "MALLARD",
    options: ["MALLARD", "AMERICAN BLACK DUCK", "NORTHERN SHOVELER", "GADWALL"],
    tips: [
      "Males are distinctive with iridescent green head, yellow bill, chestnut breast, and gray body (eBird)",
      "Females are mottled brown with orange and black splotches on the bill (eBird)",
      "White wingbars on the leading and trailing edges of the blue wing patch (eBird)",
      "Any bird with extensive white in the tail or curled feathers above the tail has some Mallard genes (eBird)",
    ],
    alt: "Mallard standing on shore",
  },
  {
    name: "mourning-dove",
    image: "assets/bird-pics/mourning-dove.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Mourning_Dove_Image_002.jpg" target="_blank" rel="noopener noreferrer">Ltshears - Trisha M Shears</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "MOURNING DOVE",
    options: [
      "MOURNING DOVE",
      "EURASIAN COLLARED-DOVE",
      "WHITE-WINGED DOVE",
      "ROCK PIGEON",
    ],
    tips: [
      "Svelte with a long, pointed tail (eBird)",
      "Plain brown overall with dark spots on wing (eBird)",
      "Juvenile is covered with pale scaly pattern, but is much larger and longer-tailed than ground doves (eBird)",
      "Listen for distinctive cooing song and whistling wings as it takes off (eBird)",
    ],
    alt: "Mourning dove perched on fence",
  },
  {
    name: "northern-cardinal",
    image: "assets/bird-pics/northern-cardinal.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Northern_Cardinal_Female-27527.jpg" target="_blank" rel="noopener noreferrer">Ken Thomas</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "NORTHERN CARDINAL",
    options: [
      "NORTHERN CARDINAL",
      "SUMMER TANAGER",
      "SCARLET TANAGER",
      "VERMILION CARDINAL",
    ],
    tips: [
      "Male is entirely red with a black face (eBird)",
      "Female is brownish overall with redder wings and tail (eBird)",
      "Usually seen in pairs or small groups near dense cover, especially thickets near forest edges (eBird)",
      "Listen for high-pitched metallic chips and series of loud, sweet whistles (eBird)",
    ],
    alt: "Northern cardinal perched on fence",
  },
  {
    name: "northern-flicker",
    image: "assets/bird-pics/northern-flicker.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Northern_Flicker_male_Yellow-shafted_RWD.jpg" target="_blank" rel="noopener noreferrer">DickDaniels</a> <a href="http://theworldbirds.org/" target="_blank" rel="noopener noreferrer">(http://theworldbirds.org/)</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "NORTHERN FLICKER",
    options: [
      "NORTHERN FLICKER",
      "RED-BELLIED WOODPECKER",
      "GILDED FLICKER",
      "YELLOW-BELLIED SAPSUCKER",
    ],
    tips: [
      "Large, brownish woodpecker with black barring on the back and black spots on the belly (eBird)",
      "Easily recognized in flight by its bright white rump (eBird)",
      "Large black crescent-shaped mark on breast (eBird)",
      "Wings and tail flash yellow or red, depending on the subspecies (eBird)",
    ],
    alt: "Northern flicker perched in tree",
  },
  {
    name: "northern-mockingbird",
    image: "assets/bird-pics/northern-mockingbird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Mimus_polyglottos_adult_02_cropped.jpg" target="_blank" rel="noopener noreferrer">Captain-tucker</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "NORTHERN MOCKINGBIRD",
    options: [
      "NORTHERN MOCKINGBIRD",
      "GRAY CATBIRD",
      "LOGGERHEAD SHRIKE",
      "BROWN THRASHER",
    ],
    tips: [
      "Medium-sized songbird with a relatively long tail, small head, and short bill (eBird)",
      "Gray above and paler whitish below (eBird)",
      "White wingbars and large white patch at the base of the primaries (eBird)",
      "Well-known for its impressive mimicry; often includes a wide range of other birds, car alarms, slamming doors, and other mechanical noises in its song (eBird)",
    ],
    alt: "Northern mockingbird perched on branch",
  },
  {
    name: "osprey",
    image: "assets/bird-pics/osprey.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Balbuzard_pecheur_Lac_de_Tunis.jpg" target="_blank" rel="noopener noreferrer">El Golli Mohamed</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "OSPREY",
    options: ["OSPREY", "RED-TAILED HAWK", "BALD EAGLE", "NORTHERN HARRIER"],
    tips: [
      "Large raptor that cruises over lakes, rivers, and coastal waterways in search of fish (eBird)",
      "Mostly white head and underparts; dark brown back (eBird)",
      "In flight, holds wings with a kink in the wrist (shaped like an 'M') (eBird)",
      "Often seen plunging feet-first into water from high in the air to grab fish (eBird)",
    ],
    alt: "Osprey perched on branch",
  },
  {
    name: "red-tailed-hawk",
    image: "assets/bird-pics/red-tailed-hawk.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Buteo_jamaicensis_-Pillar_Point_Harbor,_California,_USA-8.jpg" target="_blank" rel="noopener noreferrer">Jason Crotty</a>, <a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener noreferrer>CC BY 2.0</a>, via Wikimedia Commons"`,
    correctAnswer: "RED-TAILED HAWK",
    options: [
      "RED-TAILED HAWK",
      "SWAINSON'S HAWK",
      "FERRUGINOUS HAWK",
      "BROAD-WINGED HAWK",
    ],
    tips: [
      "Most common roadside raptor across much of North America (eBird)",
      "Often perches atop telephone poles, light posts, and edges of trees (eBird)",
      "Eastern adults have brilliant reddish-orange tail and pale underparts with obvious band of dark marks across belly (eBird)",
      "Western birds are typically darker (eBird)",
    ],
    alt: "Juvenile red-tailed hawk in field of grass",
  },
  {
    name: "red-winged-blackbird",
    image: "assets/bird-pics/red-winged-blackbird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Agelaius_phoeniceus_0110_taxo.jpg" target="_blank" rel="noopener noreferrer">Walter Siegmund</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "RED-WINGED BLACKBIRD",
    options: [
      "RED-WINGED BLACKBIRD",
      "TRICOLORED BLACKBIRD",
      "BREWER'S BLACKBIRD",
      "COMMON GRACKLE",
    ],
    tips: [
      "Most common roadside raptor across much of North America (eBird)",
      "Often perches atop telephone poles, light posts, and edges of trees (eBird)",
      "Eastern adults have brilliant reddish-orange tail and pale underparts with obvious band of dark marks across belly (eBird)",
      "Western birds are typically darker (eBird)",
    ],
    alt: "Red-winged blackbird perched on branches",
  },
  {
    name: "sandwich-tern",
    image: "assets/bird-pics/sandwich-tern.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:2020-07-18_Thalasseus_sandvicensis,_St_Marys_Island,_Northumberland_09.jpg" target="_blank" rel="noopener noreferrer">MPF</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "SANDWICH TERN",
    options: ["COMMON TERN", "ROYAL TERN", "ELEGANT TERN", "SANDWICH TERN"],
    tips: [
      "Shows a shaggy black cap in breeding plumage; nonbreeding birds develop white forehead (eBird)",
      "Strictly coastal; most commonly found on beaches and estuaries (eBird)",
      "Pale medium-sized tern with a geographically variable bill pattern: black with a distinct yellow tip in most of its range (eBird)",
      "Harsh grating calls similar to other terns (eBird)",
    ],
    alt: "Sandwich tern perched on rock in water",
  },
  {
    name: "scissor-tailed-flycatcher",
    image: "assets/bird-pics/scissor-tailed-flycatcher.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Scissor-tailed_Flycatcher_RWD7.jpg" target="_blank" rel="noopener noreferrer">DickDaniels</a> <a href="http://theworldbirds.org/" target="_blank" rel="noopener noreferrer">(http://theworldbirds.org/)</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "SCISSOR-TAILED FLYCATCHER",
    options: [
      "SCISSOR-TAILED FLYCATCHER",
      "WESTERN KINGBIRD",
      "FORK-TAILED FLYCATCHER",
      "EASTERN KINGBIRD",
    ],
    tips: [
      "Large flycatcher with an extremely long, forked tail (eBird)",
      "Pale gray overall with darker wings and a salmon-colored wash on the belly (eBird)",
      "In flight, look for brighter salmon underwings (eBird)",
      "Often seen on fenceposts and utility wires (eBird)",
    ],
    alt: "Scissor-tailed flycatcher perched on branch",
  },
  {
    name: "stellers-jay",
    image: "assets/bird-pics/stellers-jay.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Stellers_jay_-_natures_pics.jpg" target="_blank" rel="noopener noreferrer">Alan D. Wilson, www.naturespicsonline.com</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "STELLER'S JAY",
    options: [
      "STELLER'S JAY",
      "BLUE JAY",
      "CALIFORNIA SCRUB-JAY",
      "CLARK'S NUTCRACKER",
    ],
    tips: [
      "Black-and-blue with a crest (eBird)",
      "Coastal populations are the darkest, with no pale markings around the eye (eBird)",
      "Central American birds have shorter crest, limited black on the face, and very bold white markings around the eye (eBird)",
      "Loud and conspicuous; listen for harsh calls (eBird)",
    ],
    alt: "Steller's jay perched on fence",
  },
  {
    name: "white-breasted-nuthatch",
    image: "assets/bird-pics/white-breasted-nuthatch.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:White-Breasted_Nuthatch.jpg" target="_blank" rel="noopener noreferrer">http://www.naturespicsonline.com/</a>, <a href="https://creativecommons.org/licenses/by-sa/2.5" target="_blank" rel="noopener noreferrer">CC BY-SA 2.5</a>, via Wikimedia Commons`,
    correctAnswer: "WHITE-BREASTED NUTHATCH",
    options: [
      "WHITE-BREASTED NUTHATCH",
      "RED-BREASTED NUTHATCH",
      "PYGMY NUTHATCH",
      "BROWN-HEADED NUTHATCH",
    ],
    tips: [
      "The largest nuthatch in North America (eBird)",
      "Distinctive white face, black cap, and blue-gray upperparts (eBird)",
      "Rusty lower belly and undertail coverts (eBird)",
      "Creeps along tree trunks and branches, often upside-down (eBird)",
    ],
    alt: "White-breasted nuthatch perched on rock",
  },
  {
    name: "yellow-rumped-warbler",
    image: "assets/bird-pics/yellow-rumped-warbler.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Dendroica_coronata_CT.jpg" target="_blank" rel="noopener noreferrer">Cephas</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "YELLOW-RUMPED WARBLER",
    options: [
      "YELLOW-RUMPED WARBLER",
      "MAGNOLIA WARBLER",
      "PALM WARBLER",
      "PINE WARBLER",
    ],
    tips: [
      "All plumages show a bright yellow rump and yellow on the sides (eBird)",
      "Both subspecies breed in coniferous or mixed forests, often near clearings or edges (eBird)",
      "Often sallies out from a conspicuous perch to snatch insects (eBird)",
      "Most 'Audubon’s' have a yellow throat, but dull immature females can be off-white, while 'Myrtle' Warblers have a white throat that wraps around below the cheek (eBird)",
    ],
    alt: "Yellow-rumped warbler perched on branch",
  },
];

/*
  {
    name: "",
    image: "",
    imageCredit: `target="_blank" rel="noopener noreferrer"`,
    correctAnswer: "",
    options: [],
    tips: [" (eBird)"," (eBird)"," (eBird)"," (eBird)"],
    alt: "",
  },
  */

let resetBirdData = [
  {
    name: "american-robin",
    image: "assets/bird-pics/american-robin.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:2009-03-13,_American_robin_(Turdus_migratorius),_001.jpg" target="_blank" rel="noopener noreferrer">Steven Pavlov</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "AMERICAN ROBIN",
    options: [
      "AMERICAN ROBIN",
      "SPOTTED TOWHEE",
      "VARIED THRUSH",
      "EASTERN TOWHEE",
    ],
    tips: [
      "Fairly large songbird with round body, long legs, and longish tail (eBird)",
      "Gray above with warm orange underparts and blackish head (eBird)",
      "Hops across lawns and stands erect with its bill often tilted upward (eBird)",
      "Common across North America in gardens, parks, yards, golf courses, fields, pastures, and many other wooded habitats (eBird)",
    ],
    alt: "American robin standing in grass",
  },
  {
    name: "barn-swallow",
    image: "assets/bird-pics/barn-swallow.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Barn_Swallow_(34869731935).jpg" target="_blank" rel="noopener noreferrer">U.S. Fish and Wildlife Service - Midwest Region</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "BARN SWALLOW",
    options: ["BARN SWALLOW", "TREE SWALLOW", "CLIFF SWALLOW", "PURPLE MARTIN"],
    tips: [
      "A fairly large, colorful swallow with long, forked tail and dark rump (eBird)",
      "Iridescent navy-blue above with a rich orange throat and forehead (eBird)",
      "Underparts vary across range, from bright buffy-orange to whitish (eBird)",
      "Occurs in any open habitat, especially large fields and wetlands, often seen foraging in flocks (eBird)",
    ],
    alt: "Barn swallow perched on a wire",
  },
  {
    name: "belted-kingfisher",
    image: "assets/bird-pics/belted-kingfisher.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20240821_belted_kingfisher_keeney_cove_PD201201.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BELTED KINGFISHER",
    options: [
      "BELTED KINGFISHER",
      "GREEN KINGFISHER",
      "RINGED KINGFISHER",
      "BLUE JAY",
    ],
    tips: [
      "Stocky and large-headed with a shaggy crest (eBird)",
      "Bill is long, straight, thick, and pointed (eBird)",
      "Powder blue above with white underparts and blue breast band (eBird)",
      "Females have additional rusty band across belly (eBird)",
    ],
    alt: "Belted kingfisher perched on branch",
  },
  {
    name: "black-capped-chickadee",
    image: "assets/bird-pics/black-capped-chickadee.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20220923_black_capped_chickadee_posing_at_canoe_meadows_PND1343-DeNoiseAI-standard-SharpenAI-Standard.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BLACK-CAPPED CHICKADEE",
    options: [
      "BLACK-CAPPED CHICKADEE",
      "CAROLINA CHICKADEE",
      "MOUNTAIN CHICKADEE",
      "BOREAL CHICKADEE",
    ],
    tips: [
      "Tiny, plump-bodied, and big-headed (eBird)",
      "Gray overall with light buffy flanks and a contrasting head pattern: black cap, white cheek, and black throat (eBird)",
      "Short, stubby bill (eBird)",
      "Nearly identical to Carolina Chickadee, but range barely overlaps (eBird)",
    ],
    alt: "Black-capped chickadee perched in branches of a tree",
  },
  {
    name: "blue-jay",
    image: "assets/bird-pics/blue-jay.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20250126_blue_jay_housatonic_valley_wma_PD204015.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BLUE JAY",
    options: ["BLUE JAY", "STELLER'S JAY", "FLORIDA SCRUB-JAY", "GREEN JAY"],
    tips: [
      "Found year-round throughout most of eastern North America (eBird)",
      "Bright blue above and pale gray below with a fluffy crest (eBird)",
      "Black necklace and black and white markings on the wings and tail (eBird)",
      "Frequently visits bird feeders, where it is often aggressive towards other birds (eBird)",
    ],
    alt: "Blue jay perched in a tree",
  },
  {
    name: "brown-headed-cowbird",
    image: "assets/bird-pics/brown-headed-cowbird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Brown-headed_cowbird_male_(71126).jpg" target="_blank" rel="noopener noreferrer">Rhododendrites</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BROWN-HEADED COWBIRD",
    options: [
      "BROWN-HEADED COWBIRD",
      "BREWER'S BLACKBIRD",
      "COMMON GRACKLE",
      "BRONZED COWBIRD",
    ],
    tips: [
      "Stout bill, short tail and stocky body (eBird)",
      "Males are glossy black with chocolate brown head (eBird)",
      "Females are gray-brown overall, without bold streaks, but slightly paler throat (eBird)",
      "Forages by walking on the ground (eBird)",
    ],
    alt: "Brown-headed cowbird on branch",
  },
  {
    name: "brown-thrasher",
    image: "assets/bird-pics/brown-thrasher.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Brown_thrasher_in_CP_(02147).jpg" target="_blank" rel="noopener noreferrer">Rhododendrites</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0 target="_blank" rel="noopener noreferrer"">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "BROWN THRASHER",
    options: [
      "BROWN THRASHER",
      "NORTHERN MOCKINGBIRD",
      "GRAY CATBIRD",
      "CURVE-BILLED THRASHER",
    ],
    tips: [
      "Fairly large and very long-tailed, with bright rufous upperparts and heavily streaked underparts (eBird)",
      "White wingbars, staring yellow eyes, and slightly decurved bill (eBird)",
      "Usually skulky and difficult to see in shrubby habitats (eBird)",
      "Most similar to Long-billed Thrasher, but almost no range overlap (eBird)",
    ],
    alt: "Brown thrasher standing in snow",
  },
  {
    name: "canada-goose",
    image: "assets/bird-pics/canada-goose.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20231208_canada_goose_goodwin_dock_PD101660.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "CANADA GOOSE",
    options: [
      "CANADA GOOSE",
      "CACKLING GOOSE",
      "GREATER WHITE-FRONTED GOOSE",
      "SNOW GOOSE",
    ],
    tips: [
      "A large brown goose with a black neck and white chinstrap (eBird)",
      "Occurs in any open or wetland habitat, from city parks and golf courses to pristine marshes and Arctic tundra (eBird)",
      "Abundant and widespread throughout the U.S. and Canada (eBird)",
      "Listen for loud honking calls, especially as flocks migrate overhead in the classic V formation (eBird)",
    ],
    alt: "Canada goose swimming",
  },
  {
    name: "cedar-waxwing",
    image: "assets/bird-pics/cedar-waxwing.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20230608_cedar_waxwing_PD26635.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "CEDAR WAXWING",
    options: [
      "CEDAR WAXWING",
      "BOHEMIAN WAXWING",
      "NORTHERN CARDINAL",
      "EUROPEAN STARLING",
    ],
    tips: [
      "Plump, smooth-plumaged bird (eBird)",
      "Adults have a sleek crest, black mask, pale yellow wash on the belly, and yellow-tipped tail (eBird)",
      "Juveniles are drabber than adults, with coarse streaking on the breast and a reduced mask (eBird)",
      "Often gathers in large flocks, especially around fruiting trees (eBird)",
    ],
    alt: "Cedar waxwing perched on branch",
  },
  {
    name: "coopers-hawk",
    image: "assets/bird-pics/coopers-hawk.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Juvenile_cooper%27s_hawk.jpg" target="_blank" rel="noopener noreferrer">https://www.flickr.com/people/sherseydc/</a>, <a href="https://creativecommons.org/licenses/by-sa/1.0" target="_blank" rel="noopener noreferrer">CC BY-SA 1.0</a>, via Wikimedia Commons`,
    correctAnswer: "COOPER'S HAWK",
    options: [
      "COOPER'S HAWK",
      "SHARP-SHINNED HAWK",
      "RED-SHOULDERED HAWK",
      "NORTHERN GOSHAWK",
    ],
    tips: [
      "Small to medium-sized hawk with relatively short rounded wings and rounded tail (eBird)",
      "Adults are gray above with pale orange barring below; immatures are browner and streaky (eBird)",
      "Very similar to Sharp-shinned Hawk, but larger with bigger head and deeper, slower wingbeats (eBird)",
      "Often stalks feeders in search of prey (eBird)",
    ],

    alt: "Cooper's hawk perched on branch in park",
  },
  {
    name: "dark-eyed-junco",
    image: "assets/bird-pics/dark-eyed-junco.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:20231109_dark_eyed_junco_old_south_cemetery_PND09024.jpg" target="_blank" rel="noopener noreferrer">Paul Danese</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "DARK-EYED JUNCO",
    options: [
      "DARK-EYED JUNCO",
      "SONG SPARROW",
      "WHITE-THROATED SPARROW",
      "CHIPPING SPARROW",
    ],
    tips: [
      "Generally patterned with gray, white, and shades of tan (eBird)",
      "Pinkish bills and white outer tail feathers (eBird)",
      "Found in any wooded habitat in the winter, often in flocks (eBird)",
      "Usually forages on the ground for seeds, but also fond of brushy thickets or weedy fields (eBird)",
    ],
    alt: "Dark-eyed Junco perched on gravestone",
  },
  {
    name: "downy-woodpecker",
    image: "assets/bird-pics/downy-woodpecker.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Downy_woodpecker_in_GWC_(33941).jpg" target="_blank" rel="noopener noreferrer">Rhododendrites</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "DOWNY WOODPECKER",
    options: [
      "DOWNY WOODPECKER",
      "HAIRY WOODPECKER",
      "RED-COCKADED WOODPECKER",
      "YELLOW-BELLIED SAPSUCKER",
    ],
    tips: [
      "Black-and-white plumage (eBird)",
      "Very short bill, much shorter than the length of the head (eBird)",
      "Small black markings on the white outer tail feathers (eBird)",
      "Familiar visitor to backyard feeders, especially fond of suet (eBird)",
    ],
    alt: "Downy woodpecker perched on tree branch",
  },
  {
    name: "eastern-bluebird",
    image: "assets/bird-pics/eastern-bluebird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Male_Eastern_Bluebird_from_below.jpg" target="_blank" rel="noopener noreferrer">Dehaan</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "EASTERN BLUEBIRD",
    options: [
      "EASTERN BLUEBIRD",
      "WESTERN BLUEBIRD",
      "MOUNTAIN BLUEBIRD",
      "BARN SWALLOW",
    ],
    tips: [
      "Adult males are striking royal blue above with bright orange throat and breast and bright white belly (eBird)",
      "Females are paler overall; grayish with orange on breast and sides of neck, and white belly (eBird)",
      "Favors fields and open woods (eBird)",
      "Frequently perches on wires or fence posts (eBird)",
    ],
    alt: "Eastern bluebird perched on fence post",
  },
  {
    name: "european-starling",
    image: "assets/bird-pics/european-starling.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Toulouse_-_Sturnus_vulgaris_-_2012-02-26_-_1.jpg" target="_blank" rel="noopener noreferrer">PierreSelim</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "EUROPEAN STARLING",
    options: [
      "EUROPEAN STARLING",
      "COMMON GRACKLE",
      "BREWER'S BLACKBIRD",
      "RED-WINGED BLACKBIRD",
    ],
    tips: [
      "Stocky and dark overall with short tail and triangular wings (eBird)",
      "In breeding season, look for purple and green iridescence and a yellow bill (eBird)",
      "Often abundant, gathering in large flocks in open agricultural areas and towns and cities (eBird)",
      "Visits feeders, where it is often aggressive towards other birds (eBird)",
    ],
    alt: "European starling in grass",
  },
  {
    name: "great-blue-heron",
    image: "assets/bird-pics/great-blue-heron.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Ardea_herodias5.jpg" target="_blank" rel="noopener noreferrer">&quot;Mike&quot; Michael L. Baird</a>, <a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener noreferrer">CC BY 2.0</a>, via Wikimedia Commons`,
    correctAnswer: "GREAT BLUE HERON",
    options: [
      "GREAT BLUE HERON",
      "SANDHILL CRANE",
      "LITTLE BLUE HERON",
      "TRICOLORED HERON",
    ],
    tips: [
      "Huge gray heron, no other similar species in range (eBird)",
      "Large yellow-orange bill, short black plumes on head, and black and chestnut pattern on shoulder (eBird)",
      "Immatures are more brownish than adults, and have a dark crown (eBird)",
      "Occurs in almost any wetland habitat, from small ponds to marshes to saltwater bays (eBird)",
    ],
    alt: "Great blue heron standing in lake",
  },
  {
    name: "house-finch",
    image: "assets/bird-pics/house-finch.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:House_Finch-27527-2.jpg" target="_blank" rel="noopener noreferrer">Ken Thomas</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "HOUSE FINCH",
    options: ["HOUSE FINCH", "PURPLE FINCH", "CASSIN'S FINCH", "PINE SISKIN"],
    tips: [
      "Males vary in shades and intensity of red- some are yellow or orange (eBird)",
      "Females are drab gray-brown overall with plain faces and blurry streaks on underparts (eBird)",
      "Red color is mostly restricted to head and upper chest, contrasting with cold gray-brown nape, back, and wings (eBird)",
      "Pale sides show distinct brown streaks, lacking red tones (eBird)",
    ],
    alt: "House finch perched on branch",
  },
  {
    name: "killdeer",
    image: "assets/bird-pics/killdeer.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Killdeer_(Charadrius_vociferus).jpg" target="_blank" rel="noopener noreferrer">hart_curt</a>, <a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener noreferrer">CC BY 2.0</a>, via Wikimedia Commons`,
    correctAnswer: "KILLDEER",
    options: [
      "KILLDEER",
      "SPOTTED SANDPIPER",
      "SEMIPALMATED PLOVER",
      "WILSON'S PLOVER",
    ],
    tips: [
      "Slender shape with long wings and tail (eBird)",
      "Two black breast bands, unique among plovers in its range (eBird)",
      "Adults perform broken-wing displays to distract predators from their nests and young (eBird)",
      "Can be very vocal; listen for loud namesake “kill-deer” call (eBird)",
    ],
    alt: "Killdeer on rocky beach",
  },
  {
    name: "mallard",
    image: "assets/bird-pics/mallard.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Mallard_Ducks_at_Downsview_Park_13.jpg" target="_blank" rel="noopener noreferrer">Fabian Roudra Baroi</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "MALLARD",
    options: ["MALLARD", "AMERICAN BLACK DUCK", "NORTHERN SHOVELER", "GADWALL"],
    tips: [
      "Males are distinctive with iridescent green head, yellow bill, chestnut breast, and gray body (eBird)",
      "Females are mottled brown with orange and black splotches on the bill (eBird)",
      "White wingbars on the leading and trailing edges of the blue wing patch (eBird)",
      "Any bird with extensive white in the tail or curled feathers above the tail has some Mallard genes (eBird)",
    ],
    alt: "Mallard standing on shore",
  },
  {
    name: "mourning-dove",
    image: "assets/bird-pics/mourning-dove.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Mourning_Dove_Image_002.jpg" target="_blank" rel="noopener noreferrer">Ltshears - Trisha M Shears</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "MOURNING DOVE",
    options: [
      "MOURNING DOVE",
      "EURASIAN COLLARED-DOVE",
      "WHITE-WINGED DOVE",
      "ROCK PIGEON",
    ],
    tips: [
      "Svelte with a long, pointed tail (eBird)",
      "Plain brown overall with dark spots on wing (eBird)",
      "Juvenile is covered with pale scaly pattern, but is much larger and longer-tailed than ground doves (eBird)",
      "Listen for distinctive cooing song and whistling wings as it takes off (eBird)",
    ],
    alt: "Mourning dove perched on fence",
  },
  {
    name: "northern-cardinal",
    image: "assets/bird-pics/northern-cardinal.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Northern_Cardinal_Female-27527.jpg" target="_blank" rel="noopener noreferrer">Ken Thomas</a>, Public domain, via Wikimedia Commons`,
    correctAnswer: "NORTHERN CARDINAL",
    options: [
      "NORTHERN CARDINAL",
      "SUMMER TANAGER",
      "SCARLET TANAGER",
      "VERMILION CARDINAL",
    ],
    tips: [
      "Male is entirely red with a black face (eBird)",
      "Female is brownish overall with redder wings and tail (eBird)",
      "Usually seen in pairs or small groups near dense cover, especially thickets near forest edges (eBird)",
      "Listen for high-pitched metallic chips and series of loud, sweet whistles (eBird)",
    ],
    alt: "Northern cardinal perched on fence",
  },
  {
    name: "northern-flicker",
    image: "assets/bird-pics/northern-flicker.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Northern_Flicker_male_Yellow-shafted_RWD.jpg" target="_blank" rel="noopener noreferrer">DickDaniels</a> <a href="http://theworldbirds.org/" target="_blank" rel="noopener noreferrer">(http://theworldbirds.org/)</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "NORTHERN FLICKER",
    options: [
      "NORTHERN FLICKER",
      "RED-BELLIED WOODPECKER",
      "GILDED FLICKER",
      "YELLOW-BELLIED SAPSUCKER",
    ],
    tips: [
      "Large, brownish woodpecker with black barring on the back and black spots on the belly (eBird)",
      "Easily recognized in flight by its bright white rump (eBird)",
      "Large black crescent-shaped mark on breast (eBird)",
      "Wings and tail flash yellow or red, depending on the subspecies (eBird)",
    ],
    alt: "Northern flicker perched in tree",
  },
  {
    name: "northern-mockingbird",
    image: "assets/bird-pics/northern-mockingbird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Mimus_polyglottos_adult_02_cropped.jpg" target="_blank" rel="noopener noreferrer">Captain-tucker</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "NORTHERN MOCKINGBIRD",
    options: [
      "NORTHERN MOCKINGBIRD",
      "GRAY CATBIRD",
      "LOGGERHEAD SHRIKE",
      "BROWN THRASHER",
    ],
    tips: [
      "Medium-sized songbird with a relatively long tail, small head, and short bill (eBird)",
      "Gray above and paler whitish below (eBird)",
      "White wingbars and large white patch at the base of the primaries (eBird)",
      "Well-known for its impressive mimicry; often includes a wide range of other birds, car alarms, slamming doors, and other mechanical noises in its song (eBird)",
    ],
    alt: "Northern mockingbird perched on branch",
  },
  {
    name: "osprey",
    image: "assets/bird-pics/osprey.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Balbuzard_pecheur_Lac_de_Tunis.jpg" target="_blank" rel="noopener noreferrer">El Golli Mohamed</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "OSPREY",
    options: ["OSPREY", "RED-TAILED HAWK", "BALD EAGLE", "NORTHERN HARRIER"],
    tips: [
      "Large raptor that cruises over lakes, rivers, and coastal waterways in search of fish (eBird)",
      "Mostly white head and underparts; dark brown back (eBird)",
      "In flight, holds wings with a kink in the wrist (shaped like an 'M') (eBird)",
      "Often seen plunging feet-first into water from high in the air to grab fish (eBird)",
    ],
    alt: "Osprey perched on branch",
  },
  {
    name: "red-tailed-hawk",
    image: "assets/bird-pics/red-tailed-hawk.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Buteo_jamaicensis_-Pillar_Point_Harbor,_California,_USA-8.jpg" target="_blank" rel="noopener noreferrer">Jason Crotty</a>, <a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener noreferrer>CC BY 2.0</a>, via Wikimedia Commons"`,
    correctAnswer: "RED-TAILED HAWK",
    options: [
      "RED-TAILED HAWK",
      "SWAINSON'S HAWK",
      "FERRUGINOUS HAWK",
      "BROAD-WINGED HAWK",
    ],
    tips: [
      "Most common roadside raptor across much of North America (eBird)",
      "Often perches atop telephone poles, light posts, and edges of trees (eBird)",
      "Eastern adults have brilliant reddish-orange tail and pale underparts with obvious band of dark marks across belly (eBird)",
      "Western birds are typically darker (eBird)",
    ],
    alt: "Juvenile red-tailed hawk in field of grass",
  },
  {
    name: "red-winged-blackbird",
    image: "assets/bird-pics/red-winged-blackbird.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Agelaius_phoeniceus_0110_taxo.jpg" target="_blank" rel="noopener noreferrer">Walter Siegmund</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "RED-WINGED BLACKBIRD",
    options: [
      "RED-WINGED BLACKBIRD",
      "TRICOLORED BLACKBIRD",
      "BREWER'S BLACKBIRD",
      "COMMON GRACKLE",
    ],
    tips: [
      "Most common roadside raptor across much of North America (eBird)",
      "Often perches atop telephone poles, light posts, and edges of trees (eBird)",
      "Eastern adults have brilliant reddish-orange tail and pale underparts with obvious band of dark marks across belly (eBird)",
      "Western birds are typically darker (eBird)",
    ],
    alt: "Red-winged blackbird perched on branches",
  },
  {
    name: "sandwich-tern",
    image: "assets/bird-pics/sandwich-tern.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:2020-07-18_Thalasseus_sandvicensis,_St_Marys_Island,_Northumberland_09.jpg" target="_blank" rel="noopener noreferrer">MPF</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "SANDWICH TERN",
    options: ["COMMON TERN", "ROYAL TERN", "ELEGANT TERN", "SANDWICH TERN"],
    tips: [
      "Shows a shaggy black cap in breeding plumage; nonbreeding birds develop white forehead (eBird)",
      "Strictly coastal; most commonly found on beaches and estuaries (eBird)",
      "Pale medium-sized tern with a geographically variable bill pattern: black with a distinct yellow tip in most of its range (eBird)",
      "Harsh grating calls similar to other terns (eBird)",
    ],
    alt: "Sandwich tern perched on rock in water",
  },
  {
    name: "scissor-tailed-flycatcher",
    image: "assets/bird-pics/scissor-tailed-flycatcher.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Scissor-tailed_Flycatcher_RWD7.jpg" target="_blank" rel="noopener noreferrer">DickDaniels</a> <a href="http://theworldbirds.org/" target="_blank" rel="noopener noreferrer">(http://theworldbirds.org/)</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, via Wikimedia Commons`,
    correctAnswer: "SCISSOR-TAILED FLYCATCHER",
    options: [
      "SCISSOR-TAILED FLYCATCHER",
      "WESTERN KINGBIRD",
      "FORK-TAILED FLYCATCHER",
      "EASTERN KINGBIRD",
    ],
    tips: [
      "Large flycatcher with an extremely long, forked tail (eBird)",
      "Pale gray overall with darker wings and a salmon-colored wash on the belly (eBird)",
      "In flight, look for brighter salmon underwings (eBird)",
      "Often seen on fenceposts and utility wires (eBird)",
    ],
    alt: "Scissor-tailed flycatcher perched on branch",
  },
  {
    name: "stellers-jay",
    image: "assets/bird-pics/stellers-jay.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Stellers_jay_-_natures_pics.jpg" target="_blank" rel="noopener noreferrer">Alan D. Wilson, www.naturespicsonline.com</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "STELLER'S JAY",
    options: [
      "STELLER'S JAY",
      "BLUE JAY",
      "CALIFORNIA SCRUB-JAY",
      "CLARK'S NUTCRACKER",
    ],
    tips: [
      "Black-and-blue with a crest (eBird)",
      "Coastal populations are the darkest, with no pale markings around the eye (eBird)",
      "Central American birds have shorter crest, limited black on the face, and very bold white markings around the eye (eBird)",
      "Loud and conspicuous; listen for harsh calls (eBird)",
    ],
    alt: "Steller's jay perched on fence",
  },
  {
    name: "white-breasted-nuthatch",
    image: "assets/bird-pics/white-breasted-nuthatch.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:White-Breasted_Nuthatch.jpg" target="_blank" rel="noopener noreferrer">http://www.naturespicsonline.com/</a>, <a href="https://creativecommons.org/licenses/by-sa/2.5" target="_blank" rel="noopener noreferrer">CC BY-SA 2.5</a>, via Wikimedia Commons`,
    correctAnswer: "WHITE-BREASTED NUTHATCH",
    options: [
      "WHITE-BREASTED NUTHATCH",
      "RED-BREASTED NUTHATCH",
      "PYGMY NUTHATCH",
      "BROWN-HEADED NUTHATCH",
    ],
    tips: [
      "The largest nuthatch in North America (eBird)",
      "Distinctive white face, black cap, and blue-gray upperparts (eBird)",
      "Rusty lower belly and undertail coverts (eBird)",
      "Creeps along tree trunks and branches, often upside-down (eBird)",
    ],
    alt: "White-breasted nuthatch perched on rock",
  },
  {
    name: "yellow-rumped-warbler",
    image: "assets/bird-pics/yellow-rumped-warbler.jpg",
    imageCredit: `<a href="https://commons.wikimedia.org/wiki/File:Dendroica_coronata_CT.jpg" target="_blank" rel="noopener noreferrer">Cephas</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>, via Wikimedia Commons`,
    correctAnswer: "YELLOW-RUMPED WARBLER",
    options: [
      "YELLOW-RUMPED WARBLER",
      "MAGNOLIA WARBLER",
      "PALM WARBLER",
      "PINE WARBLER",
    ],
    tips: [
      "All plumages show a bright yellow rump and yellow on the sides (eBird)",
      "Both subspecies breed in coniferous or mixed forests, often near clearings or edges (eBird)",
      "Often sallies out from a conspicuous perch to snatch insects (eBird)",
      "Most 'Audubon’s' have a yellow throat, but dull immature females can be off-white, while 'Myrtle' Warblers have a white throat that wraps around below the cheek (eBird)",
    ],
    alt: "Yellow-rumped warbler perched on branch",
  },
];
